// Generated by scripts/generate-api-index.mjs. Do not edit by hand.
export type HeaderCatalogueItem = { path: string; symbols: string[] }
export const headerCatalogue: HeaderCatalogueItem[] = [
  {
    "path": "DualityEngine/Include/DualityEngine/Asset/AssetDatabase.h",
    "symbols": [
      "AssetDatabase",
      "Refresh()",
      "Register()",
      "LoadManifest()",
      "ResolvePath()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Asset/AssetMeta.h",
    "symbols": [
      "AssetMeta",
      "EnsureMetaFile()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Asset/AudioImportSettings.h",
    "symbols": [
      "AudioImportSettings",
      "Load()",
      "Save()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Asset/Material.h",
    "symbols": [
      "Material"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Asset/MaterialLoader.h",
    "symbols": [
      "MaterialLoader",
      "Load()",
      "Save()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Asset/MeshLoader.h",
    "symbols": [
      "MeshData",
      "SubMesh",
      "MeshLoader",
      "Load()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Asset/PhysicsMaterial.h",
    "symbols": [
      "PhysicsMaterial"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Asset/PhysicsMaterialLoader.h",
    "symbols": [
      "PhysicsMaterialLoader",
      "Load()",
      "Save()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Asset/ScriptableObjectLoader.h",
    "symbols": [
      "ScriptableObjectLoader",
      "Loaded",
      "Load()",
      "Save()",
      "Create()",
      "UnloadAll()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Asset/TextureImportSettings.h",
    "symbols": [
      "TextureFilterMode",
      "TextureWrapMode",
      "TextureImportSettings",
      "Load()",
      "Save()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Audio/AudioEngine.h",
    "symbols": [
      "AudioEngine",
      "Init()",
      "Shutdown()",
      "Update()",
      "Play()",
      "Stop()",
      "StopAll()",
      "SetVolume()",
      "SetPaused()",
      "IsPlaying()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Audio/WavLoader.h",
    "symbols": [
      "WavData",
      "LoadWavFile()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Core/DateTime.h",
    "symbols": [
      "DateTime"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Core/Log.h",
    "symbols": [
      "LogLevel",
      "LogEntry",
      "Log",
      "Trace()",
      "Info()",
      "Warn()",
      "Error()",
      "lock()",
      "Push()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Core/Mathf.h",
    "symbols": [
      "Mathf"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Core/Random.h",
    "symbols": [
      "Random"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/ECS/Entity.h",
    "symbols": [
      "Scene",
      "Entity",
      "AddComponent()",
      "GetComponent()",
      "HasComponent()",
      "IsValid()",
      "TryGetComponent()",
      "RemoveComponent()",
      "GetParent()",
      "GetChildren()",
      "ClearChildren()",
      "GetComponentInChildren()",
      "GetComponentInParent()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/IO/SaveSystem.h",
    "symbols": [
      "SaveSystem",
      "file()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Input/InputManager.h",
    "symbols": [
      "InputManager",
      "GetKey()",
      "GetKeyDown()",
      "GetKeyUp()",
      "GetAxis()",
      "GetPointerDown()",
      "GetPointerUp()",
      "GetPointerPosition()",
      "GetPointerScreen()",
      "BeginFrame()",
      "SetKeyState()",
      "SetAxis()",
      "SetPointer()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Input/KeyCode.h",
    "symbols": [
      "KeyCode"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Physics/BodyType.h",
    "symbols": [
      "BodyType"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Physics/PhysicsUnits.h",
    "symbols": [
      "PhysicsUnits",
      "PPU()",
      "Gravity()",
      "PhysicsGravity()",
      "ToPhysics()",
      "ToWorld()",
      "SetRuntimeOverride()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Physics/RaycastHit.h",
    "symbols": [
      "RaycastHit2D",
      "RaycastHit3D"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Project/Project.h",
    "symbols": [
      "ProjectConfig",
      "Project",
      "New()",
      "Load()",
      "Save()",
      "GetStartScenePath()",
      "GetEnabledPackagesCsv()",
      "GetScriptingDefinesCsv()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Reflection/Field.h",
    "symbols": [
      "Color4",
      "AssetRef",
      "EntityRef",
      "NestedFieldValue",
      "EnumFieldValue",
      "FieldHandle",
      "FieldValue()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Reflection/FieldSerialization.h",
    "symbols": [
      "FieldValueToJson()",
      "JsonToFieldValue()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Reflection/PropertyMacros.h",
    "symbols": []
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Reflection/Reflection.h",
    "symbols": [
      "RegisterBuiltinComponents()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Reflection/TypeRegistry.h",
    "symbols": [
      "ComponentTypeInfo",
      "TypeRegistry",
      "All()",
      "Find()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/CanvasRenderMode.h",
    "symbols": [
      "CanvasRenderMode"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/DrawHelpers2D.h",
    "symbols": [
      "IRenderer2D",
      "Scene",
      "DrawSpriteQuad()",
      "DrawNineSlice()",
      "DrawLineStrip2D()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/IRenderer2D.h",
    "symbols": [
      "IRenderer2D",
      "Init()",
      "Shutdown()",
      "BeginFrame()",
      "EndFrame()",
      "BeginScene()",
      "EndScene()",
      "DrawQuad()",
      "DrawText()",
      "MeasureText()",
      "LoadFont()",
      "LoadTexture()",
      "UnloadAllTextures()",
      "UnloadAllFonts()",
      "GetDrawCallCount()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/IRenderer3D.h",
    "symbols": [
      "IRenderer3D",
      "Init()",
      "Shutdown()",
      "BeginScene()",
      "EndScene()",
      "DrawMesh()",
      "GetSubMeshCount()",
      "LoadTexture()",
      "LoadMesh()",
      "UnloadAllTextures()",
      "UnloadAllMeshes()",
      "GetDrawCallCount()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/MeshPrimitive.h",
    "symbols": [
      "MeshPrimitive"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/N3DS/Citro2DRenderer.h",
    "symbols": [
      "Citro2DRenderer",
      "Init()",
      "Shutdown()",
      "BeginFrame()",
      "EndFrame()",
      "BeginScene()",
      "EndScene()",
      "DrawQuad()",
      "DrawText()",
      "MeasureText()",
      "LoadFont()",
      "UnloadAllFonts()",
      "LoadTexture()",
      "UnloadAllTextures()",
      "TargetFor()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/N3DS/Citro3DRenderer.h",
    "symbols": [
      "Citro3DRenderer",
      "PrimitiveGpuMesh",
      "Init()",
      "Shutdown()",
      "SetScreenTargets()",
      "BeginScene()",
      "EndScene()",
      "DrawMesh()",
      "GetSubMeshCount()",
      "LoadTexture()",
      "LoadMesh()",
      "UnloadAllTextures()",
      "UnloadAllMeshes()",
      "TargetFor()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/OpenGL/GLFontLoader.h",
    "symbols": [
      "GLFont",
      "GLFontLoader",
      "LoadFontFromFile()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/OpenGL/GLShaderProgram.h",
    "symbols": [
      "GLShaderProgram",
      "Init()",
      "Shutdown()",
      "Bind()",
      "Unbind()",
      "GetUniformLocation()",
      "GetAttribLocation()",
      "SetUniformMat4()",
      "SetUniformVec4()",
      "SetUniformInt()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/OpenGL/GLTextureLoader.h",
    "symbols": [
      "GLTextureLoader"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/OpenGL/GLVertexArray.h",
    "symbols": [
      "GLVertexArray",
      "Init()",
      "Shutdown()",
      "Bind()",
      "Unbind()",
      "SetVertexData()",
      "AddFloatAttribute()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/OpenGL/OpenGLRenderer2D.h",
    "symbols": [
      "OpenGLRenderer2D",
      "Init()",
      "Shutdown()",
      "BeginFrame()",
      "EndFrame()",
      "BeginScene()",
      "EndScene()",
      "DrawQuad()",
      "DrawText()",
      "MeasureText()",
      "LoadFont()",
      "LoadTexture()",
      "UnloadAllTextures()",
      "UnloadAllFonts()",
      "BeginCustomView()",
      "DrawGrid()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/OpenGL/OpenGLRenderer3D.h",
    "symbols": [
      "OpenGLRenderer3D",
      "Init()",
      "Shutdown()",
      "BeginScene()",
      "EndScene()",
      "SetDepthWriteEnabled()",
      "DrawMesh()",
      "GetSubMeshCount()",
      "LoadTexture()",
      "LoadMesh()",
      "UnloadAllTextures()",
      "UnloadAllMeshes()",
      "UploadGpuMesh()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/PrimitiveMeshes.h",
    "symbols": [
      "MeshVertex",
      "GetPrimitiveMesh()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/ProjectionType.h",
    "symbols": [
      "ProjectionType"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/SceneRenderer.h",
    "symbols": [
      "RenderScreen()",
      "RenderScreen3D()",
      "GetActiveSpriteTexture()",
      "ResolveSpriteTexture()",
      "ResolveMeshTexture()",
      "ResolveMeshMaterial()",
      "ResolveMeshGeometry()",
      "ShouldRenderOnScreen()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/Screen.h",
    "symbols": [
      "Screen"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/TextAlignment.h",
    "symbols": [
      "TextAlignment"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/UIAnchor.h",
    "symbols": [
      "UIAnchor",
      "UIAnchorPresetToMinMaxPivot()",
      "LegacyUIAnchorToRectTransform()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/UILayoutType.h",
    "symbols": [
      "UILayoutType"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Renderer/UIRenderer.h",
    "symbols": [
      "FindOwningCanvas()",
      "IsUIElementOnCanvas()",
      "EnsureUIElementsHaveCanvas()",
      "ResolveUIRect()",
      "UpdateUIInteractions()",
      "RenderScreenUI()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scene/ActiveComponent.h",
    "symbols": [
      "ActiveComponent"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scene/Behaviour.h",
    "symbols": [
      "Behaviour",
      "Entity()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scene/Components.h",
    "symbols": [
      "Behaviour",
      "NameComponent",
      "TagComponent",
      "TransformComponent",
      "SpriteRendererComponent",
      "MeshRendererComponent",
      "SpriteFlipbookComponent",
      "CameraComponent",
      "PhysicsRaycaster2DComponent",
      "PhysicsRaycaster3DComponent",
      "ScriptInstance",
      "BehaviourComponent",
      "Rigidbody2DComponent",
      "BoxCollider2DComponent",
      "CircleCollider2DComponent",
      "CapsuleCollider2DComponent",
      "PolygonCollider2DComponent",
      "Rigidbody3DComponent",
      "BoxCollider3DComponent",
      "SphereCollider3DComponent",
      "CapsuleCollider3DComponent",
      "HierarchyComponent",
      "PrefabInstanceComponent",
      "LayerComponent",
      "AudioSourceComponent",
      "UIRectComponent",
      "UIImageComponent",
      "UIButtonComponent",
      "UITextComponent",
      "CanvasComponent",
      "UILayoutGroupComponent",
      "UISliderComponent",
      "UIToggleComponent",
      "UIInputFieldComponent",
      "SpriteSheetAnimatorComponent",
      "TilemapComponent",
      "LineRendererComponent",
      "FollowTargetComponent",
      "AudioListenerComponent",
      "ParticleSystemComponent",
      "Particle"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scene/Layer.h",
    "symbols": [
      "Layer"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scene/PhysicsRaycaster.h",
    "symbols": [
      "UpdatePhysicsRaycasterInteractions()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scene/PointerEventHandlers.h",
    "symbols": [
      "PointerEventData",
      "IPointerEnterHandler",
      "IPointerExitHandler",
      "IPointerDownHandler",
      "IPointerUpHandler",
      "IPointerClickHandler",
      "OnPointerEnter()",
      "OnPointerExit()",
      "OnPointerDown()",
      "OnPointerUp()",
      "OnPointerClick()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scene/PrefabSerializer.h",
    "symbols": [
      "PrefabSerializer",
      "Save()",
      "Apply()",
      "Revert()",
      "Unpack()",
      "Duplicate()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scene/Scene.h",
    "symbols": [
      "TransformComponent",
      "Scene",
      "CreateEntity()",
      "DestroyEntity()",
      "GetPrimaryCamera()",
      "GetScreenRoot()",
      "EnsureScreenRoot()",
      "GetParent()",
      "GetChildren()",
      "ClearChildren()",
      "GetHierarchyTraversalOrder()",
      "SetSiblingIndex()",
      "GetWorldTransform()",
      "FindEntityInScreen()",
      "ResolveEntityLayer()",
      "TryResolveEntityScreen()",
      "IsEffectivelyActive()",
      "Raycast2D()",
      "Raycast3D()",
      "ScreenPointToRay3D()",
      "ScreenPointToWorld2D()",
      "RaycastPoint2D()",
      "OnRuntimeStart()",
      "OnRuntimeUpdate()",
      "OnRuntimeStop()",
      "OnApplicationFocus()",
      "OnApplicationPause()",
      "OnApplicationQuit()",
      "Clear()",
      "SiblingListFor()",
      "IsValid()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scene/SceneManager.h",
    "symbols": [
      "SceneManager"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scene/SceneRuntimeSystems.h",
    "symbols": [
      "Scene",
      "TilemapData",
      "TilemapLoader",
      "Load()",
      "UpdateSceneRuntimeSystems()",
      "ClearSceneRuntimeSystems()",
      "GetParticlePool()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scene/SceneSerializer.h",
    "symbols": [
      "SceneSerializer",
      "Serialize()",
      "Deserialize()",
      "SerializeToJson()",
      "DeserializeFromJson()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scene/SceneValidator.h",
    "symbols": [
      "Scene",
      "SceneValidationSeverity",
      "SceneValidationIssue",
      "SceneValidationResult",
      "SceneValidator",
      "HasErrors()",
      "Validate()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/AudioSource.h",
    "symbols": [
      "AudioSource"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/Camera.h",
    "symbols": [
      "Camera"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/Collider2D.h",
    "symbols": [
      "Collider2D"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/Collider3D.h",
    "symbols": [
      "Collider3D"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/Debug.h",
    "symbols": [
      "Debug"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/EngineServices.h",
    "symbols": [
      "EngineServices",
      "long()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/EntityLayer.h",
    "symbols": [
      "EntityLayer"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/Input.h",
    "symbols": [
      "Input"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/LineRenderer.h",
    "symbols": [
      "LineRenderer",
      "GetLinePoint()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/MeshRenderer.h",
    "symbols": [
      "MeshRenderer"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/Rigidbody2D.h",
    "symbols": [
      "Rigidbody2D"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/Rigidbody3D.h",
    "symbols": [
      "Rigidbody3D"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/ScriptAudio.h",
    "symbols": [
      "ScriptAudio"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/ScriptContext.h",
    "symbols": [
      "ScriptContext"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/ScriptDebug.h",
    "symbols": [
      "ScriptDebug"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/ScriptModule.h",
    "symbols": [
      "ScriptFactoryEntry"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/ScriptPhysics2D.h",
    "symbols": [
      "ScriptPhysics2D"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/ScriptPhysics3D.h",
    "symbols": [
      "ScriptPhysics3D"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/ScriptRegistry.h",
    "symbols": [
      "ScriptRegistry",
      "Clear()",
      "Register()",
      "IsRegistered()",
      "TryCreate()",
      "Count()",
      "GetAllClassNames()",
      "GetFields()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/ScriptScene.h",
    "symbols": [
      "ScriptScene",
      "Entity()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/ScriptableObject.h",
    "symbols": [
      "ScriptableObject"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/ScriptableObjectModule.h",
    "symbols": [
      "ScriptableObjectFactoryEntry"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/ScriptableObjectRegistry.h",
    "symbols": [
      "ScriptableObjectRegistry",
      "Clear()",
      "Register()",
      "Find()",
      "All()"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/SpriteFlipbook.h",
    "symbols": [
      "SpriteFlipbook"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/SpriteRenderer.h",
    "symbols": [
      "SpriteRenderer"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/Time.h",
    "symbols": [
      "Time"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/Transform.h",
    "symbols": [
      "Transform"
    ]
  },
  {
    "path": "DualityEngine/Include/DualityEngine/Scripting/UIWidgets.h",
    "symbols": [
      "UIButton",
      "UIRect",
      "UIImage",
      "UIText"
    ]
  }
]
